spring:
  application:
    name: "eventarz-eureka"

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
#    TODO: preferIpAddress only really comes into play on Kubernetes, but is it necessary to have it both here and on services?
    preferIpAddress: true
    hostname: localhost